title: Werts·We
email: werts-we@qq.com
description: werts's repo!
github_username:  werts

all_categories: [
["skill", "/posts/skill.html","glyphicon-wrench"],
["blog", "/posts/blog.html", "glyphicon-list-alt"],
["mood", "/posts/mood.html", "glyphicon-heart"],
["resume", "/posts/resume.html", "glyphicon-user"],
["contact", "/posts/contact.html", "glyphicon-earphone"],
["program", "/posts/program.html", "glyphicon-file"],
["plugins", "/posts/plugins.html", "glyphicon-list-alt"]
]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
